---
  title: "analysis"
date: "8/23/2019"
output: html_document
---
  
  ## Setup
  
```{r setup}
# Import libraries
library(tidyverse)
library(ggridges)
library(pwr) 
library(grid)
library(gtable)
library(boot)
library(bootES)
library(ggbeeswarm)
library(tidybayes)
library(cowplot)
library(broom)
library(scales)

# Set the plot themes
theme_set(theme_tidybayes() + panel_border() + background_grid())

# Import data
df = read.csv("../results/pilot/CSV/TidyR.csv")
dfp = read.csv("../results/pilot/CSV/participantInfoTidyR.csv")

# Update numeric and character variable types
df$value = as.numeric( as.character(df$value ))
df$userDriven = as.character(df$userDriven) 

dfp$value = as.numeric( as.character(dfp$value ))
  
# Refactor the factor variables into the right order
df$taskType_f = factor(
  df$taskType, 
  levels=c("cluster","linear regression", "quadratic regression","skyline", "outlier"),
  labels=c("Cluster","Linear\nRegression", "Quadratic\nRegression","Multivariate\nOptimization", "Outlier")
)

df$measure_f = factor(
  df$measure, 
  levels = c("accuracy","secondsOnTask", "confidence", "difficulty"),
  labels = c("Accuracy","Time (seconds)", "Confidence", "Difficulty")
)

df$userLabel = factor(
  df$userDriven, 
  levels = c("supported","manual"),
  labels = c("CS","UD")
)

# Create new variables
df$custom_group = ifelse(df$taskDifficulty == 'easy', "easy", "medium_hard")

# Filter the dataframe into some commonly used smaller sets
df_medium_hard = df %>%
  filter(custom_group == "medium_hard" & measure_f == "Accuracy")

df_easy = df %>%
  filter(custom_group == "easy" & measure_f == "Accuracy")

df_acc = df %>% 
  filter(measure_f=="Accuracy")

df_time = df %>% 
  filter(measure_f=="Time (seconds)")

# Set plotting colors
userDriven.colors = c("UD" ="#05b4dd", "CS" = "#f4aa4a")
```



```{r}
# Generates the paired wilcox test for a taskType with a given dataset
wtest = function(data, type) {
  t_manual = data %>% 
    filter(taskType_f == type & userDriven == "manual") %>%
    arrange(prolificId, taskId, dataset)
  
  t_supported = data %>% 
    filter(taskType_f == type & userDriven == "supported")%>%
    arrange(prolificId, taskId, dataset)
  
  print(type)
  test = wilcox.test(t_manual$value, t_supported$value, paired = TRUE)
  print(test)
  
  return(
    list(
      statistic = test$statistic,
      p.value = test$p.value,
      sample.size1 = t_manual %>% nrow(),
      sample.size2 = t_supported %>% nrow()
    )
  )
}

med_hard_cluster_wilcox = wtest(df_medium_hard, "Cluster")
med_hard_LR_wilcox = wtest(df_medium_hard, "Linear\nRegression")
med_hard_outlier_wilcox = wtest(df_medium_hard, "Outlier")
med_hard_QR_wilcox = wtest(df_medium_hard, "Quadratic\nRegression")
med_hard_MO_wilcox = wtest(df_medium_hard, "Multivariate\nOptimization")
```


```{r}
# Generates the bootstrapped effect size for a given type and measure
estext = function(measure_, type) {
  # Filter the dataset based on measure and type
  filtered_data = df %>% 
    filter(measure_f == measure_ & taskType_f == type)
  
  # Get the levels
  lvs = levels(as.factor(filtered_data[["userDriven"]]))

  # Do the bootstrap
  b = bootES(
    filtered_data,
    data.col="value",
    group.col="userDriven",
    contrast=lvs, # normal cases c(group1=1, group2=-1), but for 2 groups, it's simplified.
    effect.type="cohens.d"
  )
  
  # Return the data
  cat(paste0(type, "\n"))
  cat( "d=", round( b$t0, 2), "~",
       "[", round( b$bounds[1], 2), ",",
       round( b$bounds[2], 2), "]",  "\n",  "\n",
       sep="")
  
  return(
    list(
      lower = b$bounds[1], 
      mean = b$t0, 
      upper = b$bounds[2]
    )
  )
}

d_acc_cluster = estext("Accuracy", "Cluster")
d_acc_LR = estext("Accuracy", "Linear\nRegression")
d_acc_outlier = estext("Accuracy", "Outlier")
d_acc_QR = estext("Accuracy", "Quadratic\nRegression")
d_acc_MO = estext("Accuracy", "Multivariate\nOptimization")
```



```{r fig.width=4, fig.height=4 }
gridLines = function(x) { 
 if (max(as.numeric(x))<2) seq(0,1, .25) 
  else if (max(as.numeric(x))<10) seq(1, 5, 1) 
  else (c(0,100))
}
axisRange = function(x) { 
  if (max(as.numeric(x))<2) c(0,1)
   else  if (max(as.numeric(x))<10) c(0,5)
  else (c(0,100))
}

# Get the main chart data
filteredData = df %>%
  filter(custom_group=="medium_hard" & measure_f=="Accuracy")

# Get the data for the statistics
d_values = bind_rows(d_acc_cluster, d_acc_LR, d_acc_outlier, d_acc_QR, d_acc_MO)
statistics = bind_rows(med_hard_cluster_wilcox, med_hard_LR_wilcox, med_hard_outlier_wilcox, med_hard_QR_wilcox, med_hard_MO_wilcox)
joined_stats = rownames_to_column(statistics) %>% 
  inner_join(rownames_to_column(d_values)) %>% 
  mutate(taskType_f = c("Cluster", "Linear\nRegression", "Outlier", "Quadratic\nRegression", "Multivariate\nOptimization"))
joined_stats$taskType_f = factor(
  joined_stats$taskType_f,
  levels = c("Cluster","Linear\nRegression", "Quadratic\nRegression","Multivariate\nOptimization", "Outlier")
)

# Make the full chart minus the CI labels
g = ggplot(filteredData, aes(x = userLabel, y = value, fill = userLabel, color = userLabel)) +
  geom_violin(show.legend = FALSE) +
  geom_hline(yintercept = seq(0,1,0.25), color = "white") + 
  coord_flip() +
  stat_summary(fun.data = "mean_cl_boot", geom="linerange", size=1,alpha=1, color = "#5c5c5c", show.legend = FALSE) +
  facet_grid(taskType_f ~ .) +
  scale_color_manual(values=userDriven.colors) +
  scale_fill_manual(values=userDriven.colors) +
  scale_y_continuous(breaks = gridLines, limits = axisRange, expand = c(0, 0.01)) + 
  theme(
    panel.spacing.x = unit(0, "pt"),
    panel.border = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "white"),
    panel.spacing.y = unit(1, "lines"),
    axis.title.x = element_blank(),
    axis.line.x = element_blank(),
    axis.text.x = element_text(size = 6),
    axis.title.y = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_text(size = 5, hjust = 1, margin = margin(0, unit = "pt")),
    strip.text.y = element_text(angle = 0, hjust = 0, face = "bold", margin = margin(0, unit = "pt")),
    strip.background = element_blank(),
    legend.position = "none"
  )


stt = ggplot_build(g)$data[[3]]

stt$PANEL = as.numeric( as.character(stt$PANEL ))
stt$taskType = ifelse((stt$PANEL <2), "Cluster", ifelse((stt$PANEL <3), "Linear\nRegression", ifelse((stt$PANEL <4), "Quadratic\nRegression", ifelse((stt$PANEL <5), "Multivariate\nOptimization", "Outlier"))))

stt$taskType_f = factor(stt$taskType, levels=c("Cluster","Linear\nRegression", "Quadratic\nRegression","Multivariate\nOptimization", "Outlier"));

stt$userLabel = ifelse(stt$group=="2", 'UD', 'CS')

# Add the geom_text with the calculated information
g + geom_point(data = stt, aes(x = userLabel, y = y), color = "#5c5c5c", size = 4, alpha=0.5, show.legend = FALSE) +
  geom_text(
    data = stt,
    aes(
      x = userLabel, 
      label = paste(
        round(ymin,3), ' - ',
        round(y,3), ' - ',
        round(ymax,3),
        sep=" "
      ),
      vjust = ifelse(userLabel == "UD", -0.7, 2)
    ),
    color = "#5c5c5c",
    y = 0, 
    size = 2,
    hjust = 0
  ) +
  geom_text(
    data = joined_stats, 
    aes(
      label = paste0("n=", sample.size1, ", W=", statistic, ", p=", scientific(p.value, 3), ", d=", round(mean, 3)),
      fill = NULL, 
      color = NULL,
      x = "", 
      y = 1
    ),
    color = "#5c5c5c",
    size = 2,
    hjust = 1
  ) +
  scale_x_discrete(limits = c("", "CS", "UD"))

# Save the plot to pdf
ggsave("accuracy_medium_hard.pdf", width = 4, height = 4, units = "in")
```




```{r fig.width=8, fig.height=4}

gridLines = function(x) { 
 if (max(as.numeric(x))<2) c(0,1)
  else if (max(as.numeric(x))<10) seq(1, 5, 1) 
  else (c(0,100))
}


for (diff_level in c("easy", "medium_hard")) {
  df_data =  df %>%
    filter(custom_group==diff_level & (measure == "accuracy" | measure == "secondsOnTask"))
  g = df_data %>% 
    ggplot( aes(x=userLabel, y=value, fill = userLabel, color = userLabel) ) +
      facet_grid(taskType_f ~ measure_f, scales="free")+
      geom_violin(show.legend=FALSE) +
      stat_summary(fun.data = "mean_cl_boot", geom="linerange", size=1,alpha=1, colour = "#5c5c5c", show.legend=FALSE) +
      stat_summary(fun.data = "mean_cl_boot", colour = "#5c5c5c", size = 1, alpha=0.5, show.legend=FALSE) +
      coord_flip() +
      scale_color_manual(values=userDriven.colors)+
      scale_fill_manual(values=userDriven.colors)+
      theme(strip.text.y = element_text(angle = 0))+
      scale_y_continuous(breaks = gridLines, limits = axisRange)+
    theme(
      panel.spacing.x = unit(0, "pt"),
      panel.border = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color = "white"),
      panel.spacing.y = unit(1, "lines"),
      axis.title.x = element_blank(),
      axis.line.x = element_blank(),
      axis.text.x = element_text(size = 6),
      axis.title.y = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.y = element_text(size = 5, hjust = 1, margin = margin(0, unit = "pt")),
      strip.text.y = element_text(angle = 0, hjust = 0, face = "bold", margin = margin(0, unit = "pt")),
      strip.background = element_blank(),
      legend.position = "none"
    )
  
  stt = ggplot_build(g)$data[[3]]
  
  print (stt)
  
  stt$PANEL = as.numeric( as.character(stt$PANEL ))
  stt$taskType = ifelse((stt$PANEL <3), "Cluster", ifelse((stt$PANEL <5), "Linear\nRegression", ifelse((stt$PANEL <7), "Quadratic\nRegression", ifelse((stt$PANEL <9), "Multivariate\nOptimization", "Outlier"))))
  
  stt$taskType_f = factor(stt$taskType, levels=c("Cluster","Linear\nRegression", "Quadratic\nRegression","Multivariate\nOptimization", "Outlier"));
  
  stt$measure = ifelse((stt$PANEL %% 2 == 1), "Accuracy", "Time (seconds)")
  stt$measure_f = factor(stt$measure, levels=c("Accuracy","Time (seconds)"));
  
  stt$userLabel = ifelse(stt$group=="2", 'UD', 'CS')
  
  
  print (stt)
  
  
  g + geom_text(
    data = stt,
    aes(x =userLabel, y = 0, hjust = 0,label = paste(round(y,3) , '[' , round(ymin,3) ,  ',' , round(ymax,3) , ']',sep=" ")),
    color = "#5c5c5c",size=2,
    vjust = 1
    ) +
    facet_grid(taskType_f ~ measure_f,scales = "free") +
    theme(
      panel.background = element_rect(fill = NA),
      panel.border = element_blank(),
      panel.ontop = TRUE,
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color = "white"),
      panel.spacing.y = unit(1, "lines"),
      axis.line.y = element_blank(),
      axis.line.x = element_blank(),
      axis.ticks.y = element_blank()
    ) 

  filename = paste0("results_", diff_level, ".pdf")
  ggsave(filename, width = 10, height = 5, units = "in")
}

 
```



```{r  fig.width=7, fig.height=8}

dfp_filtered = dfp %>% 
  filter(type=="feedback")

# Feedback histogram point and line data
mean_cl_boot_data = dfp_filtered %>%
  group_by(measure) %>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$value))))
 
# Feedback histogram
ggplot(dfp_filtered) +
  geom_histogram(aes(x = value), binwidth = 1, boundary = 0.5) +
  geom_point(
    data = mean_cl_boot_data,
    aes(x = Mean, y = -25),
      colour = "#5c5c5c",
    alpha=0.5
  ) +
  geom_line(
    data = reshape2::melt(mean_cl_boot_data),
    aes(x = value, y = -25),
    colour = "#5c5c5c",
    alpha=1
  ) + 
  geom_text(
    data = mean_cl_boot_data,
    aes(label = paste(round(Mean,3) , '[' , round(Lower,3) ,  ',' , round(Upper,3) , ']', sep=" "), y = -25, x = 0.5,  hjust = 0),
    colour = "#5c5c5c",
    size = 2
  ) +
  facet_grid(measure ~ .)+
  # scale_x_discrete(limits = c(1,2,3,4,5)) + 
  scale_y_continuous(limits = c(-50,100), breaks = c(0,100))+
  theme(
    panel.background = element_rect(fill = NA),
    panel.border = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "white"),
    panel.spacing.y = unit(1, "lines"),
    axis.title.y.left = element_blank(),
    axis.text.y.left = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(hjust = 0),
    strip.text.y = element_text(angle = 0)
  ) 

filename <- paste("survey_responses.pdf")
ggsave(filename, width = 7, height = 8, units = "in")

```

```{r fig.width=10, fig.height=8}
for (diff_level in c("easy", "medium_hard")) {
  # Confidence and difficulty histogram point and line data
  mean_cl_boot_conf_diff = df %>%
    filter(custom_group == diff_level) %>%
    filter(measure_f=="Confidence" | measure_f=="Difficulty") %>%
    group_by(measure_f, userLabel, taskType_f) %>%
    do(data.frame(rbind(Hmisc::smean.cl.boot(.$value))))
  
  df_data_conf_diff= df %>%
    filter(custom_group == diff_level) %>%
    filter(measure_f=="Confidence" | measure_f=="Difficulty")
  
  reshape2::melt(mean_cl_boot_conf_diff)
  
  # Confidence and difficulty histograms
  ggplot(df_data_conf_diff, aes(x=value) ) +
    geom_histogram(aes(y=..density.., fill = userLabel, color = userLabel), binwidth = 1, boundary = 0.5, show.legend = FALSE) + 
    geom_point(
      data = mean_cl_boot_conf_diff,
  
      aes(x = Mean, y = -0.1),
      colour = "#5c5c5c"
    ) +
    geom_line(
      data = reshape2::melt(mean_cl_boot_conf_diff),
      aes(x = value, y = -0.1),
       colour = "#5c5c5c",
      alpha=1
    ) +
    geom_text(
      data = mean_cl_boot_conf_diff,
      aes(label = paste(round(Mean,3) , '[' , round(Lower,3) ,  ',' , round(Upper,3) , ']', sep=" "), y = -0.1, x = 5.5, hjust=1),
      colour = "#5c5c5c",
      size = 2
    ) +
    facet_grid(taskType_f + userLabel ~ measure_f, scales="free") +
    theme(strip.text.y = element_text(angle = 0)) +
    scale_y_continuous(expand = c(0, 0.1)) +
    scale_color_manual(values=userDriven.colors) +
    scale_fill_manual(values=userDriven.colors) +
    theme(
      panel.background = element_rect(fill = NA),
      panel.border = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(color = "white"),
      panel.spacing.y = unit(1, "lines"),
      axis.title.y.left = element_blank(),
      axis.text.y.left = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      strip.background = element_blank(),
      strip.text.y = element_text(hjust = 0)
    ) 
  
  filename <- paste0("confidence_difficulty_", diff_level, ".pdf")
  ggsave(filename, width = 10, height = 8, units = "in")
}
```


```{r fig.width=8, fig.height=12}
gridLines = function(x) { 
 if (max(as.numeric(x))<2) c(0,1)
  else if (max(as.numeric(x))<10) seq(1, 5, 1) 
  else (c(0,100))
}
axisRange = function(x) { 
  if (max(as.numeric(x))<2) c(0,1)
   else  if (max(as.numeric(x))<10) c(0,5)
  else (c(0,100))
}

df_data =  df %>%
  filter (measure == "accuracy" | measure == "secondsOnTask")

mean_cl_boot = df_data %>%
  group_by(measure_f, taskType_f, orig_group) %>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$value))))
  
ggplot(df_data, aes(x = 1, y=value, fill = userLabel, color = userLabel) ) +
  facet_grid(orig_group ~ measure_f, scales="free")+
  geom_violin(show.legend=FALSE) +
  coord_flip() +
  scale_y_continuous(breaks = gridLines, limits = axisRange) + 
  scale_x_continuous(limits = c(-0.5,2)) + 
  geom_point(
    data = mean_cl_boot,
    aes(y = Mean, x = 1, fill = NULL, color = NULL),
    colour = "#5c5c5c"
  ) +
  geom_line(
    data = reshape2::melt(mean_cl_boot),
    aes(y = value, x = 1, fill = NULL, color = NULL),
    colour = "#5c5c5c",
    alpha=0.5
  ) +
  geom_text(
    data = mean_cl_boot,
    aes(label = paste(round(Mean,3) , '[' , round(Lower,3) ,  ',' , round(Upper,3) , ']', sep=" "), y = 0, x = 0, fill = NULL, color = NULL),
    colour = "#5c5c5c",
    hjust=0
  ) +
  scale_color_manual(values=userDriven.colors)+
  scale_fill_manual(values=userDriven.colors)+
  theme(
    panel.spacing.x = unit(0, "pt"),
    panel.border = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(color = "white"),
    panel.spacing.y = unit(1, "lines"),
    axis.title.x = element_blank(),
    axis.line.x = element_blank(),
    axis.text.x = element_text(size = 6),
    axis.title.y = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    strip.text.y = element_text(angle = 0, hjust = 0, face = "bold", margin = margin(0, unit = "pt")),
    strip.background = element_blank(),
    legend.position = "none"
  )

filename = paste("results_allTasks.pdf")
ggsave(filename, width = 10, height = 20, units = "in")
 
```

















